Document: fail2ban-p2p
Title: Debian fail2ban-p2p Manual
Author: <insert document author here>
Abstract: This manual describes what fail2ban-p2p is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/fail2ban-p2p/fail2ban-p2p.sgml.gz

Format: postscript
Files: /usr/share/doc/fail2ban-p2p/fail2ban-p2p.ps.gz

Format: text
Files: /usr/share/doc/fail2ban-p2p/fail2ban-p2p.text.gz

Format: HTML
Index: /usr/share/doc/fail2ban-p2p/html/index.html
Files: /usr/share/doc/fail2ban-p2p/html/*.html
